import time
import pyfiglet
import matplotlib.pyplot as plt
import numpy as np
import random as r
import getpass
abc=["a","b","c","d","e","f","g","h","i","j"]
bcd=["k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
cde=["A","B","C","D","E","F","G","H","I","J"]
dep=["K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
lop=["0","1","2","3","4","5","6","7","8","9"]
fod=["/","?","%","@","&","#","$","*"]
g=r.choice(abc)
h=r.choice(bcd)
i=r.choice(cde)
j=r.choice(dep)
k=r.choice(lop)
l=r.choice(fod)
xxx=g+l+k+j+i+h
def syllabous():
    print("=====================================================================================================================================")
    print("             Syllabus                                  Subject                               Subject Code     Subject Type    Credit")
    print("=====================================================================================================================================")
    print("1.)             ⬇              Demystifying Artificial Intelligence And Machine Learning         CS3321           Theory          3")
    print("2.)             ⬇              Python Programming                                                CS3322           Theory          3")
    print("3.)             ⬇              Python Programming Lab                                            CS3344          Practical        1")
    print("4.)             ⬇              Data Structure And Programming                                    CS3301           Theory          4")
    print("5.)             ⬇              Discreate Design Structure                                        CS3302           Theory          3")
    print("6.)             ⬇              Database Management System                                        CS3305           Theory          3")
    print("7.)             ⬇              Data Structure Programming Lab                                    CS3340          Practical        1")
    print("8.)             ⬇              Digital Electronics                                               EC3341          Practical        1")
    print("9.)             ⬇              Oracle/SQL Server Lab                                             CS3342          Practical        1")
    print("10.)            ⬇              Project Lab1                                                      CS3346          Practical        2")
    print("11.)            ⬇              Value Added Programe                                              VP3301          Practical        1")
    print("12.)            ⬇              Digital Electronic                                                EC3306           Theory          3")
    print("13.)            ⬇              Internship Presentation                                           CS3371          Practical        1")
    print("14.)            ⬇              General Proficiency                                               GP3301           Theory          1")
    print("=====================================================================================================================================")
    academic()
def assignment():
        logo=pyfiglet.figlet_format("Assignment")
        print(logo)
        print("\n\t<------- Acadmic --------->")
        print("\n\t1.) Assignment")
        print("\n\t2.) Question Bank")
        print("\n\t3.) Knowledge Bank")
        print("\n\t4.) Tutorial ")
        print("\n\t5.) Study Material")
        print("\n\t6.) Class Test")
        print("\n\t7.) Internal")
        print("\n\t8.) Open Book WriteUp")
        print("\n\t9.) Exit")
        aca_under=int(input("Choose Any Options [1,9] ==> "))
        if(aca_under==1):
            print("================================================================================================================================================================")
            print("Download  Employee Name      Submit Date   Submit Start-End Time    Class Subject       Type      Assignment Subject      Uploaded Date    Max Marks    Obtained ")
            print("================================================================================================================================================================")
            print("   ⬇       ABCDEFGHIJ         19/09/2020   ----------------------      VAP(111)       Assignment      Assignment1           19/09/2020        15           11")
            print("   ⬇       ABCDEFGHIJ         19/09/2020   ----------------------    Digital Elec.    Assignment      Assignment1           19/09/2020        15           12")
            print("   ⬇       ABCDEFGHIJ         30/09/2020   ----------------------       Python        Assignment      Assignment1           29/09/2020        15           15")
            print("   ⬇       ABCDEFGHIJ         01/10/2020   ----------------------        DDS          Assignment      Assignment1           29/09/2020        15           13")
            print("   ⬇       ABCDEFGHIJ         01/10/2020   ----------------------       AIML          Assignment      Assignment1           29/09/2020        15           13")
            print("   ⬇       ABCDEFGHIJ         30/09/2020   ----------------------       DBMS          Assignment      Assignment1           29/09/2020        15           13")
            print("   ⬇       ABCDEFGHIJ         16/10/2020   ----------------------      VAP(111)       Assignment      Assignment2           30/09/2020        15           NA")
            print("   ⬇       ABCDEFGHIJ         29/10/2020   ----------------------      VAP(111)       Assignment      Assignment3           16/10/2020        15           NA")
            print("   ⬇       ABCDEFGHIJ         19/09/2020   ----------------------    Data Structure   Assignment      Assignment1           29/10/2020        15           14")
            print("   ⬇       ABCDEFGHIJ         06/11/2020   ----------------------       DBMS          Assignment      Assignment2           05/11/2020        15           13")
            print("   ⬇       ABCDEFGHIJ         23/11/2020   ----------------------    Digital Elec.    Assignment      Assignment2           06/11/2020        15           12")
            print("   ⬇       ABCDEFGHIJ         28/11/2020   ----------------------       Python        Assignment      Assignment2           23/11/2020        15           15")
            print("   ⬇       ABCDEFGHIJ         30/11/2020   ----------------------       AIML          Assignment      Assignment2           26/11/2020        15           NA")
            print("   ⬇       ABCDEFGHIJ         28/11/2020   ----------------------    Data Structure   Assignment      Assignment2           26/11/2020        15           13")
            print("================================================================================================================================================================")
            assignment()
        elif(aca_under==2):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==3):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==4):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==5):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==6):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==7):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==8):
            print("Data Not Found!........")
            assignment()
        elif(aca_under==9):
            academic()
        else:
            print("Please Enter Valid Options......")
            assignment()
def academic():
    logo=pyfiglet.figlet_format("Academic")
    print(logo)
    print("\n\t<------- Acadmic --------->")
    print("\n\t1.) Time Table")
    print("\n\t2.) Assignment")
    print("\n\t3.) Syllabus")
    print("\n\t4.) FeedBack")
    print("\n\t5.) Semester Registration")
    print("\n\t6.) Exit")
    ch=int(input("Choose Any Options [1,6] ==> "))
    if(ch==1):
        logo=pyfiglet.figlet_format("Time-Table")
        print(logo)
        print("=======================================================================================================================================================================")
        print("Days/Period	(P1)09:00-09:55	          (P2)09:55-10:50         (P3)10:50-11:45	 (P4)11:45-12:40	(P6)13:35-14:30	       (P7)14:30-15:25	(P8)15:25-16:20")
        print("=======================================================================================================================================================================")
        print("Monday	         Data Structure 	Digital Electronics	 Python Programming        -------------        Python Programming	  Project Lab	   Project Lab")
        print("\n")
        print("Tuesday	          Project Lab	            Project Lab		  ----------------     	   -------------             AIML                     VAP              VAP")
        print("\n")
        print("Wednesday	Data Structure 	         Data Structure      Discreate Design Structure	  Data Structure	     DBMS	            Oracle           Oracle")
        print("\n")
        print("Thrusday	--------------                DBMS	           Data Structure              DDS		     DDS                   -----------         AIML")
        print("\n")
        print("Frieday	     Digital Electronics	Digital Electronics  Discreate Design Structure	  --------------	 -----------------	     DBMS         -----------")
        print("\n")
        print("Saturday	    AIML	        Digital Electronics  Database Management System	  Data Structure 	Python Programming	 -------------	        DE")
        print("=======================================================================================================================================================================")
        academic()
    elif(ch==2):
        assignment()
    elif(ch==3):
        syllabous()
    elif(ch==4):
        print("Data Not Found!.......")
        academic()
    elif(ch==5):
        print("You Have Alreay Responed!.......")
        academic()
    elif(ch==6):
        abc()
    else:
        print("Please Enter Valid Options......")
        academic()
def fee():
    logo=pyfiglet.figlet_format("Fee")
    print(logo)
    print("\n\t<------- Fee --------->")
    print("\n\t1.) Fee Submission")
    print("\n\t2.) Transaction History")
    print("\n\t3.) Exit")
    ch=int(input("Choose Any Options [1,3] ==> "))
    if(ch==1):
        print("\n\t<------- Academic Fee Details( Amount in --------->\n")
        print("====================================================================================================================================")
        print("       Sem/Year          Fee Head          Current Dues Amount        Scholarship/Discounnt        Paid Amount        Balance Amount  ")
        print("====================================================================================================================================")
        print("1.)    3rd Sem       Branch Change Fee         15,000.00                      0.00                    0.00               15,000.00")
        print("2.)    3rd Sem         TUITION Fee             42,000.00                      0.00                  40,000.00             2,500.00")
        print("3.)    3rd Sem       ACADEMIC SERVICES         17,500.00                      0.00                  12,500.00             5,000.00")
        print("4.)    3rd Sem           EXAM FEE              2,500.00                       0.00                   2,500.00               0.00")
        print("5.)    4th Sem         TUITION FEE             42,500.00                      0.00                  22,500.00            20,000.00")
        print("6.)    4th Sem       ACADEMIC SERVICES         17,500.00                      0.00                    0.00               17,500.00")
        print("7.)    4th Sem           EXAM FEE              2,500.00                       0.00                    0.00                2,500.00")
        print("====================================================================================================================================")
        fee()
    elif(ch==2):
        print("No Data Found......")
        fee()
    elif(ch==3):
        abc()
    else:
        print("Please Enter valid options.....")
        fee()
def circular():
    logo=pyfiglet.figlet_format("Circular")
    print(logo)
    print("\n\t<------- Circular Details --------->")
    print("\n\t1.) Circular")
    print("\n\t2.) Exit")
    ch=int(input("Choose Any Options [1,2] ==> "))
    if(ch==1):
        print("=======================================================================================================================================")
        print("                                             Subject                                   Date  Form          Date To         Circular By")
        print("=======================================================================================================================================")
        print("\n")
        print("1.)    Transport Notice for 1st Year student Only                                      22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("2.)    Pin click will be conducting drive for post Graduates and under Graduates       22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("3.)    Diploma 1st year New Time Table Effective From 23.12.2020                       22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("4.)    Pharmacy 1st year New Time Table Efffective From23.12.2020                      22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("5.)    Nutrition & Dietetics 1st year New Time Table Effective From 23.12.2020         22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("6.)    MCA 1st year New Time Table Effective Form23.12.2020                            22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("7.)    BMRIT 1st year New Time Table Effective Form23.12.2020                          22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("8.)    BJMC 1st year New Time Table Effective Form23.12.2020                           22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("9.)    BCA 1st year New Time Table Effective Form23.12.2020                            22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("10.)   B.TECH 1st year New Time Table Effective Form23.12.2020                         22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("11.)   B.Sc PCM 1st year New Time Table Effective Form23.12.2020                       22/12/2020        31/12/2020       ABCDEFGH XTSE")
        print("=======================================================================================================================================")
        circular()
    elif(ch==2):
        abc()
    else:
        print("Please Enter valid options.....")
        circular()
def exam():
    logo=pyfiglet.figlet_format("Exam")
    print(logo)
    print("\n\t<------- Exam --------->")
    print("\n\t1.) Sessional/TA Marks Statement")
    print("\n\t2.) Ext Sem .Exam Apply")
    print("\n\t3.) Summer Sem/Back Paper Apply")
    print("\n\t4.) Online Exam")
    print("\n\t5.) Transaction History")
    print("\n\t6.) Exit")
    ch=int(input("Choose Any Options [1,6] ==> "))
    if(ch==1):
        print("\n\t<------- Sessional/Teacher Assessment Marks Statement --------->\n")
        print("Student Name")
        print("SANJEEV KUMAR PRAJAPATI\n")
        print("Father Name")
        print("PQRST ABC\n")
        print("Enrollment No")
        print("QU2701101925\n")
        print("Course")
        print("B.Tech\n")
        print("Branch")
        print("(Hons.)Computer Science & Engineering with\nSpecialization in AI and Machine Learning in\nCollaboration with Xebia")
        def exam_in():
            a=int(input("\n\tSemester : "))
            b=input("\n\tSubject Type[Theory,Practical] : ").lower()
            c=int(input("\n\tSessional/TA : "))
            d=input("\n\tFor Exit Press E and Continue C[E/C] :").lower()
            if(a==1 and b=='theory' and c==1 and d=='c'):
                print("\n")
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Engineering Physics                    PH3101                  Sessioonal-1                    45                50")
                print("2.)  Mathematics - 1                        MH3102                  Sessioonal-1                    40                50")
                print("3.)  Professional Communication             EG3102                  Sessioonal-1                    39                50")
                print("4.)  Basic of Computer and C Programming    CS3101                  Sessioonal-1                    43                50")
                print("5.)  Basic Machanical Engineering           ME3102                  Sessioonal-1                    42                50")
                print("6.)  Disaster Management                    CE3101                  Sessioonal-1                    42                50")
                print("==============================================================================================================================")
                exam_in()
            elif(a==1 and b=='theory' and c==2 and d=='c'):
                print("\n")
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Engineering Physics                    PH3101                  Sessioonal-2                    46                50")
                print("2.)  Mathematics - 1                        MH3102                  Sessioonal-2                    50                50")
                print("3.)  Professional Communication             EG3102                  Sessioonal-2                    41                50")
                print("4.)  Basic of Computer and C Programming    CS3101                  Sessioonal-2                    46                50")
                print("5.)  Basic Machanical Engineering           ME3102                  Sessioonal-2                    34                50")
                print("6.)  Disaster Management                    CE3101                  Sessioonal-2                    36                50")
                print("==============================================================================================================================")
                exam_in()
            elif(a==1 and b=='theory' and c>2 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==1 and b=='practical' and c==1 and d=='c'):
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Engineering Physics Lab                PH3140                  Lab Record -1                    14                15")
                print("2.)  Engineering Physics Lab                PH3140                    Quiz -1                        10                15")
                print("3.)  Professional Communication lab         EG3140                  Lab Record -1                    13                15")
                print("4.)  Professional Communication lab         EG3140                    Quiz -1                        12                15")
                print("5.)  Basic of Computer and C Programming    CS3140                  Lab Record -1                    14                15")
                print("6.)  Basic of Computer and C Programming    CS3140                    Quiz -1                        09                15")
                print("7.)  Personality Development Program        VP3101                  Assignment -1                    30                75")
                print("==============================================================================================================================")
                exam_in()
            elif(a==1 and b=='practical' and c==2 and d=='c'):
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Engineering Physics Lab                PH3140                  Lab Record -2                    15                15")
                print("2.)  Engineering Physics Lab                PH3140                    Quiz -2                        12                15")
                print("3.)  Professional Communication lab         EG3140                  Lab Record -2                    14                15")
                print("4.)  Professional Communication lab         EG3140                    Quiz -2                        14                15")
                print("5.)  Basic of Computer and C Programming    CS3140                  Lab Record -2                    14                15")
                print("6.)  Basic of Computer and C Programming    CS3140                    Quiz -2                        12                15")
                print("7.)  Personality Development Program        VP3101                  Assignment -2                    32                75")
                print("==============================================================================================================================")
                exam_in()
            elif(a==1 and b=='practical' and c>2 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==2 and b=='theory' and c==2 and d=='c'):
                print("\n")
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Environment Studies                    CY3205                  Sessioonal-2                    21                25")
                print("2.)  Human Values and Ethics                PS3101                  Sessioonal-2                    20                25")
                print("3.)  Graph Theory And Probability           CS3203                  Sessioonal-2                    24                25")
                print("4.)  Advance C Programming                  CS3206                  Sessioonal-2                    20                25")
                print("5.)  HTML5 & CSS                            CS3204                  Sessioonal-2                    22                25")
                print("6.)  Web And Digital Analytics              CS3205                  Sessioonal-2                    22                25")
                print("==============================================================================================================================")
                exam_in()
            elif(a==2 and b=='theory' and c==1 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==2 and b=='theory' and c>2 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==2 and b=='practical' and c==1 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==2 and b=='practical' and c>2 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==2 and b=='practical' and c==2 and d=='c'):
                print("\n")
                print("==============================================================================================================================")
                print("                Subject                  Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("==============================================================================================================================")
                print("1.)  Value Added Program                    VP3201                  Sessioonal-2                    24                25")
                print("2.)  HTML5 & CSS                            CS3243                    Quiz -2                       14                15")
                print("3.)  Advance C Programming                  CS3242                    Quiz -2                       14                15")
                print("4.)  Web And Digital Analytics              CS3244                    Quiz -2                       12                15")
                print("==============================================================================================================================")
                exam_in()
            elif(a==3 and b=='theory' and c==1 and d=='c'):
                print("====================================================================================================================================================================")
                print("                Subject                                                        Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("====================================================================================================================================================================")
                print("1.)  Demystifying Artificial Intelligence and Machine Learning                    CS3321                  Mid Sem Exam                    34                40")
                print("2.)  Python Programming                                                           CS3322                  Mid Sem Exam                    38                40")
                print("3.)  Data Structure And Programming                                               CS3301                  Mid Sem Exam                    36                40")
                print("4.)  Discreate Design Structure                                                   CS3302                  Mid Sem Exam                    37                40")
                print("5.)  Database Management System                                                   CS3305                  Mid Sem Exam                    33                40")
                print("6.)  Digital Electronics                                                          EC3306                  Mid Sem Exam                    39                40")
                print("====================================================================================================================================================================")
                exam_in()
            elif(a==3 and b=='theory' and c>1 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(a==3 and b=='practical' and c==1 and d=='c'):
                print("====================================================================================================================================================================")
                print("                Subject                                                        Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("====================================================================================================================================================================")    
                print("1.)  Python Programming Lab                                                       CS3344                     Quiz -1                     19                  20")
                print("2.)  Data Structure Programming Lab                                               CS3340                     Quiz -1                     17                  20")
                print("3.)  Digital Electronics Lab                                                      EC3341                     Quiz -1                     16                  20")
                print("4.)  Oracle/SQL Server Lab                                                        CS3342                     Quiz -1                     16                  20")
                print("5.)  Project Lab 1                                                                CS3346                 Presetation -1                  22                  25")
                print("====================================================================================================================================================================")
                exam_in()
            elif(a==3 and b=='practical' and c==2 and d=='c'):
                print("====================================================================================================================================================================")
                print("                Subject                                                        Subject Code        Sessional/Teacher Assessment     Obtained Marks     Maximum Marks")
                print("====================================================================================================================================================================")
                print("1.)  Python Programming Lab                                                       CS3344                     Quiz -2                     20                  20")
                print("2.)  Data Structure Programming Lab                                               CS3340                     Quiz -2                     20                  20")
                print("3.)  Digital Electronics Lab                                                      EC3341                     Quiz -2                     18                  20")
                print("4.)  Oracle/SQL Server Lab                                                        CS3342                     Quiz -2                     19                  20")
                print("5.)  Project Lab 1                                                                CS3346                 Presetation -2                  24                  25")
                print("====================================================================================================================================================================")
                exam_in()
            elif(a==3 and b=='practical' and c>2 and d=='c'):
                print("\tData Not Found.............")
                exam_in()
            elif(d=='e'):
                exam()
            else:
                print("Please Enter Valid Option........")
                exam_in()
        exam_in()
    elif(ch==2):
        print("You Are Already Responsed.........")
        exam()
    elif(ch==3):
        print("No Data Found.........")
        exam()
    elif(ch==4):
        print("No Data Found.........")
        exam()
    elif(ch==5):
        print("No Data Found.........")
        exam()
    elif(ch==6):
        print("No Data Found.........")
        abc()
    else:
        print("Please Enter Valid Options......")
        exam()
def event():
    logo=pyfiglet.figlet_format("Event")
    print(logo)
    print("\n\t<------- Event --------->")
    print("\n\t1.) PROP Selection")
    print("\n\t2.) PROP Attendance Details")
    print("\n\t3.) Exit")
    ch=int(input("Choose Any Options [1,3] ==> "))
    if(ch==1):
        print("\n\t<------- Selected PROPs --------->\n")
        print("==================================================================================================")
        print("     Priority                   Society/Club                            Subject")
        print("==================================================================================================")
        print("1.)     1                     Technical Society          Agni Club Vehicle Design and Fabrication")
        print("2.)     2                         Sports                               Sports Carom")
        print("==================================================================================================")
        event()
    elif(ch==2):
        print("No Data Found.........")
        event()
    elif(ch==3):
        abc()
    else:
        print("Please Enter Valid Options......")
        event()
# Analysis With Graph
def analysis_show():
    print("\n")
    print("=======================================================================================================================================================================")
    print("\t\t\t\t\tTotal Attendance Percent\t\t\tDue Amount/Credit Amount (Current Academic Year)")
    print("\t\t\t\t\t\t\t   100%\t\t\t\t\t\t\t\t   140000/77500")
    print("\t\t\t\t   Company Visited/Placed Student\t\t\t\t\t\t\tTotal Carry/CGPA")
    print("\t\t\t\t\t\t\t   0/0\t\t\t\t\t\t\t\t\t-------")
    print("=======================================================================================================================================================================")
    print("<----------- Personal Information -------------->")
    print("\n")	
    print("Registration Date :	27/07/2019	Student ID :	89070160	University Roll No:	2701101925")
    print("Name :	SANJEEV KUMAR PRAJAPATI	     Father's Name :	PQRST XYZ	    Mother's Name :	ABCDEFGH")
    print("DOB :	10/02/2001	Mobile No. :	79XXXXXX14	Email ID :	sk5672934@gmail.com")
    print("Blood Group:	O+ve	Lateral Entry:	No	Enrollment No.	QU2701101925")
    print("=======================================================================================================================================================================")
    print("\n<--------- Program Information --------------->\n")
    print("Student Type :	Regular	University :	Quantum University	College:	School of Technology")
    print("CourseType :	Engineering	Course :	B.Tech	Current Year/Sem :	3")
    print("Branch :	(Hons) Computer Science & Engineering with Specialization in AI and Machine Learning in Collaboration with Xebia	Section :	N/A")
    print("=======================================================================================================================================================================")
    print("\n<-------- Educational Information ----------->\n")
    print("High School % :	88.6	Intermediate % :	74.8	Graduation %: -------")	
    print("=======================================================================================================================================================================")
    print("\n<-------- Address Information --------------->\n")
    print("Permanent Address :	S/O Pqrst Abc,Shiv Nagar,Haridwar,Dehradun , Uttarakhand,India	Correspondance Address:	S/O Pqrst Abc,Shiv Nagar,Haridwar,Dehradun , Uttarakhand,India")
    print("=======================================================================================================================================================================")
    print("\n<-------- Facility Information -------------->\n")
    print("Hostel/Room : --------		Route/Bus Stop : --------")
    print("=======================================================================================================================================================================")
    print("\n<-------- Family Information ---------------->\n")
    print("Father's Mobile No :	74XXXXXX99	Father's Occupation :	service	        Father's Department : ------")	
    print("Mother's Mobile No :	74XXXXXX99	Mother's Occupation :	HOUSE WIFE	Mother's Department : ------")
    print("=======================================================================================================================================================================")
    print("\n<-------- Award Information ----------------->\n")
    print("Award : -----")	
    print("Level : -----		Distinction : ------")	
    print("=======================================================================================================================================================================")
    print("\n<-------- Mentor Details -------------------->\n")
    print("Mentor : -------		Contact No : --------		Email : --------")	
    print("=======================================================================================================================================================================")
    print("\n<-------- Minor/Open-Elective, PROP Details -------->\n")
    print("Type :	N/A	Minor/Open-Elective :	N/A	PROP Selected :	Agni Club: Vehicle Design and Fabrication")
    print("=======================================================================================================================================================================")
    print("<----------- Subject Wise Attendance ------------>\n")
    print("=======================================================================================================================================================================")
    print("                                 Subject                              SubjectCode   Total Day   Attend Day    Percentage")
    print("=======================================================================================================================================================================")
    print("1	Demystifying Artificial Intelligence and Machine Learning(S)	CS3321	       44	   44	          100")
    print("2	Python Programming(S)	                                        CS3322	       38	   38	          100")
    print("3	Python Programming Lab(L)	                                CS3344	       25	   25	          100")
    print("4	Data Structure and Programming(S)	                        CS3301	       57	   57	          100")
    print("5	Discrete Design Structure(S)	                                CS3302         59	   59       	  100")
    print("6	Database Management System(S)	                                CS3305	       59	   59	          100")
    print("7	Data Structure Programming Lab(L)	                        CS3340	       26	   26	          100")
    print("8	Digital Electronics Lab(L)	                                EC3341	       28	   28	          100")
    print("9	Oracle/SQL Server Lab(L)	                                CS3342	       30	   30	          100")
    print("10	Project Lab I(L)	                                        CS3346	       56	   56	          100")
    print("11	Value Added Program III(L)	                                VP3301	       28	   28	          100")
    print("12	Digital Electronics(S)	                                        EC3306	       40	   40	          100")
    print("=======================================================================================================================================================================")
    present=[44,48,25,57,59,59,26,28,30,56,28,40]
    total=[44,48,25,57,59,59,26,28,30,56,28,40]
    percent=[100,100,100,100,100,100,100,100,100,100,100,100,]
    x=np.arange(len(present))
    plt.scatter(x,present,color='blue')
    plt.scatter(x+0.12,total,color='red')
    plt.scatter(x+0.12+0.12,percent,color='orange')
    plt.legend(['Present','Total','Percent'])
    plt.title("Subject Wise Attendance")
    plt.xticks([i+0.25 for i in range(12)],['CS3321','CS3322','CS3344','CS3302','CS3305','CS3340','CS3340','EC3341','CS3342','CS3346','VP3301','EC33206'])
    plt.xlabel("Subject Code")
    plt.ylabel("Subject %")
    #line plot
    present=[44,48,25,57,59,59,26,28,30,56,28,40]
    total=[44,48,25,57,59,59,26,28,30,56,28,40]
    percent=[100,100,100,100,100,100,100,100,100,100,100,100,]
    x=np.arange(len(present))
    plt.plot(x,present,color='blue')
    plt.plot(x+0.12,total,color='red')
    plt.plot(x+0.12+0.12,percent,color='orange')
    plt.legend(['Present','Total','Percent'])
    plt.title("Subject Wise Attendance")
    plt.xticks([i+0.25 for i in range(12)],['CS3321','CS3322','CS3344','CS3302','CS3305','CS3340','CS3340','EC3341','CS3342','CS3346','VP3301','EC33206'])
    plt.xlabel("Subject Code")
    plt.ylabel("Subject %")
    plt.show()
    plt.show()
    #pie plot
    a=[44,48,25,57,59,59,26,28,30,56,28,40]
    b=['CS3321','CS3322','CS3344','CS3302','CS3305','CS3340','CS3340','EC3341','CS3342','CS3346','VP3301','EC33206']
    plt.pie(a,labels=b,explode=(0.2,0.2,0,0,0,0,0,0,0,0,0,0.2),autopct='%1.1f%%')
    plt.title("Subject wise Attendance Details")
    plt.axis('equal')
    plt.legend(['CS3321','CS3322','CS3344','CS3302','CS3305','CS3340','CS3340','EC3341','CS3342','CS3346','VP3301','EC33206'])
    plt.xlabel("Subject Code")
    plt.ylabel("Subject %")
    plt.figure(figsize=[5,10])
    #bar plot
    plt.bar(x,present,color='blue',width=0.12)
    plt.bar(x+0.12,total,color='red',width=0.12)
    plt.bar(x+0.12+0.12,percent,color='orange',width=0.12)
    plt.legend(['Present','Total','Percent'])
    plt.xticks([i+0.25 for i in range(12)],['CS3321','CS3322','CS3344','CS3302','CS3305','CS3340','CS3340','EC3341','CS3342','CS3346','VP3301','EC33206'])
    plt.title("Subject wise Attendance Details")
    plt.xlabel("Subjects")
    plt.xlabel("Subject Code")
    plt.ylabel("Subject %")
    plt.show()
    plt.show()

# Dislay Months Record
def months():
    a=input("\n\tEnter Months Name : ").lower()
    if(a=='august'):
        logo=pyfiglet.figlet_format("August")
        print(logo)
        print("=======================================================================================================================================================================")
        print("	                    Subject             1       2       3       4       5       6       7       8       9       10      11      12      13      14      15\n\t\t\t\t\t\t16      17      18      19      20      21      22      23      24      25      26      27      28      29      30")
        print("=======================================================================================================================================================================")
        print("1	CS3321 (Demystifying AIML	        N	N	N	N	N	N	N	N	N	N	N	N	P	N	N	\n\t\t\t\t\t\tN	N	P	N	P	N	P	N	N	P	N	P	N	P	N")	
        print("2	CS3322 (Python Programming(S))	        N	N	N	N	N	N	N	N	N	N	N	N	N	P	N	\n\t\t\t\t\t\tN	P	N	N	N	P	P	N	P	N	N	N	P	P	N")	
        print("3	CS3344 (Python Programming Lab(L))	N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N")	
        print("4	CS3301 (Data Structure a	        N	N	N	N	N	N	N	N	N	N	N	N	P	N	N	\n\t\t\t\t\t\tN	P	N	P	P	N	P	N	N	N	P	P	P	P	N")	
        print("5	CS3302 (Discrete Design Structure	N	N	N	N	N	N	N	N	N	N	N	N	P	P	N	\n\t\t\t\t\t\tN	N	P	P	P	P	N	N	N	P	P	P	N	N	N")	
        print("6	CS3305 (Database Management System(S))	N	N	N	N	N	N	N	N	N	N	N	N	P	P	N	\n\t\t\t\t\t\tN	N	N	P	P	P	P	N	N	N	P	P	P	P	N")	
        print("7	CS3340 (Data Structure Programming Lab	N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	P,P	N	N	N	N")	
        print("8	EC3341 (Digital Electronics Lab(L))	N	N	N	N	N	N	N	N	N	N	N	N	N	P,P	N	\n\t\t\t\t\t\tN	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N")	
        print("9	CS3342 (Oracle/SQL Server Lab(L))	N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N")	
        print("10	CS3346 (Project Lab I(L))	        N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	P,P	P,P	N	N	N	N	N	P,P	P,P	N	N	N	N	N")	
        print("11	VP3301 (Value Added Program III(L))	N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	P,P	N	N	N	N	N")	
        print("12	EC3306 (Digital Electronics(S))   	N	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	P	N	N	N	N	P,P	N	P	N	N	N	N	P,P	N")	
        print("=======================================================================================================================================================================")
        b=int(input("\n\tExit Pres 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='september'):
        logo=pyfiglet.figlet_format("September")
        print(logo)
        print("=======================================================================================================================================================================")
        print("	                    Subject             1       2       3       4       5       6       7       8       9       10      11      12      13      14      15\n\t\t\t\t\t\t16      17      18      19      20      21      22      23      24      25      26      27      28      29      30")
        print("=======================================================================================================================================================================")
        print("1        CS3321 (Demystifying AI And ML   	P	N	P	N	P	N	N	P	N	P	N	P	N	N	P	\n\t\t\t\t\t\tN	P	N	P	N	N	P	N	P	N	P	N	N	P	N")
        print("2	CS3322 (Python Programming(S))	        N	N	N	P	P	N	P	N	N	N	P	P	N	P	N	\n\t\t\t\t\t\tN	N	P	P	N	P	N	N	N	P	P	N	P	N	N")
        print("3	CS3344 (Python Programming Lab(L))	N	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	\n\t\t\t\t\t\tN	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N")
        print("4	CS3301 (Data Structure and Programming	N	N	P	P	P	N	N	N	P	P	N	P	N	P	N	\n\t\t\t\t\t\tP	P	N	P	N	P	N	P	P	N	P	N	P	N	P")
        print("5	CS3302 (Discrete Design Structur)	P	N	P	N	N	N	N	N	P	P,P	P	N	N	N	N	\n\t\t\t\t\t\tP	P,P	P	N	N	N	N	P	P,P	P	N	N	N	N	P")
        print("6	CS3305 (Database Management System(S))	N	N	P	P	P	N	N	N	P	P	P	P	N	N	N	\n\t\t\t\t\t\tP	P	P	P	N	N	N	P	P	P	P	N	N	N	P")
        print("7	CS3340 (Data Structure Programming Lab	N	N	N	N	N	N	N	N	P,P	N	N	N	N	N	N	\n\t\t\t\t\t\tP,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P")
        print("8	EC3341 (Digital Electronics Lab(L))	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	\n\t\t\t\t\t\tN	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N")
        print("9	CS3342 (Oracle/SQL Server Lab(L))	N	N	N	N	N	N	N	N	P,P	N	N	N	N	N	N	\n\t\t\t\t\t\tP,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P")
        print("10	CS3346 (Project Lab I(L))	        P,P	N	N	N	N	N	P,P	P,P	N	N	N	N	N	P,P	P,P	\n\t\t\t\t\t\tN	N	N	N	N	P,P	P,P	N	N	N	N	N	P,P	P,P	N")
        print("11	VP3301 (Value Added Program III(L))	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N")
        print("12	EC3306 (Digital Electronics(S))	N	N	N	N	P,P	N	P	N	N	N	N	P,P	N	P	N	N	\n\t\t\t\t\t\tN	N	P,P	N	P	N	N	N	N	P,P	N	P	N	N       N")
        print("=======================================================================================================================================================================")
        b=int(input("\n\tExit Pres 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='october'):
        logo=pyfiglet.figlet_format("October")
        print(logo)
        print("=======================================================================================================================================================================")
        print("	                    Subject             1       2       3       4       5       6       7       8       9       10      11      12      13      14      15\n\t\t\t\t\t\t16      17      18      19      20      21      22      23      24      25      26      27      28      29      30")
        print("=======================================================================================================================================================================")
        print("1	CS3321 (Demystifying AIML	        P	N	P	N	N	P	N	P	N	P	N	N	P	N	P	\n\t\t\t\t\t\tN	P	N	N	N	N	N	N	N	N	N	P	N	P	N")
        print("2	CS3322 (Python Programming(S))	        N	N	P	N	P	N	N	N	P	P	N	P	N	N	N	\n\t\t\t\t\t\tP	P	N	N	N	N	N	N	N	N	N	N	N	N	P")
        print("3	CS3344 (Python Programming Lab     	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("4	CS3301 (Data Structure and Programming	P	N	P	N	P	N	P	P	N	P	N	P	N	P	P	\n\t\t\t\t\t\tN	P	N	N	N	N	N	N	N	N	N	N	P	P	N")
        print("5	CS3302 (Discrete Design Structure(S))	P,P	N	N	N	N	N	P	P,P	P	N	N	N	N	P	P,P	\n\t\t\t\t\t\tP	N	N	N	N	N	N	N	N	N	N	N	P	P,P	P")	
        print("6	CS3305 (Database Management System(S))	P	N	P	N	N	N	P	P	P	P	N	N	N	P	P	\n\t\t\t\t\t\tP	P	N	N	N	N	N	N	N	N	N	N	P	P	P")	
        print("7	CS3340 (Data Structure Programming Lab	N	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	P,P	N	N")	
        print("8	EC3341 (Digital Electronics Lab(L))	N	N	N	N	N	N	N	N	P,P	N	N	N	N	N	N	\n\t\t\t\t\t\tP,P	N	N	N	N	N	N	N	N	N	N	N	N	P,P")	
        print("9	CS3342 (Oracle/SQL Server Lab(L))	N	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	P,P	N	N")	
        print("10	CS3346 (Project Lab I(L))	        N	N	N	N	P,P	P,P	N	N	N	N	N	P,P	P,P	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	P,P	N	N	N")	
        print("11	VP3301 (Value Added Program III(L))	N	N	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	P,P	N	N	N")	
        print("12	EC3306 (Digital Electronics(S))	        N	N	P,P	N	P	N	N	N	N	P,P	N	P	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")	
        print("=======================================================================================================================================================================")
        b=int(input("\n\tExit Pres 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='november'):
        logo=pyfiglet.figlet_format("November")
        print(logo)
        print("=======================================================================================================================================================================")
        print("	                    Subject             1       2       3       4       5       6       7       8       9       10      11      12      13      14      15\n\t\t\t\t\t\t16      17      18      19      20      21      22      23      24      25      26      27      28      29      30")
        print("=======================================================================================================================================================================")
        print("1	CS3321 (Demystifying AIML        	N	N	P	N	P	N	N	N	N	P	N	P	N	N	N	\n\t\t\t\t\t\tN	P	N	P	N	P	N	N	P	N	P	N	P	N	N")
        print("2	CS3322 (Python Programming(S))	        N	P	N	N	N	P	P	N	P	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	P	N	P	N	N	N	N	P	N	P")
        print("3	CS3344 (Python Programming Lab(L))	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	P	N	N	N	N	N	N	P")
        print("4	CS3301 (Data Structure and Programming	N	P	N	P	P	N	P	N	P	N	P	P	N	N	N	\n\t\t\t\t\t\tN	N	P	P	N	P	N	P	N	P	P	N	P	N	P")
        print("5	CS3302 (Discrete Design Structure)	N	N	N	P	P,P	P	N	N	N	N	P	P,P	N	N	N	\n\t\t\t\t\t\tN	N	P	P,P	P	N	N	N	N	P	P,P	P	N	N	N")
        print("6	CS3305 (Database Management System(S))	N	N	N	P	P	P	P	N	N	N	P	P	N	N	N	\n\t\t\t\t\t\tN	N	P	P	P	P	N	N	N	P	P	P	P	N	N")
        print("7	CS3340 (Data Structure Programming)	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	\n\t\t\t\t\t\tN	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N")
        print("8	EC3341 (Digital Electronics Lab(L))	N	N	N	N	N	P,P	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N")
        print("9	CS3342 (Oracle/SQL Server Lab(L))	N	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	\n\t\t\t\t\t\tN	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N")
        print("10	CS3346 (Project Lab I(L))	        N	P,P	P,P	N	N	N	N	N	P,P	P,P	N	N	N	N	N	\n\t\t\t\t\t\tP,P	N	N	N	N	N	P,P	P,P	N	N	N	N   	N    P,P")
        print("11	VP3301 (Value Added Program III(L))	N	N	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	\n\t\t\t\t\t\tN	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N")
        print("12	EC3306 (Digital Electronics(S))	        N	P	N	N	N	N	P,P	N	P	N	N	N	N	N	N	s\n\t\t\t\t\t\tN	N	N	N	P,P	N	P	N	N	N	N	P,P	N       N")
        print("=======================================================================================================================================================================")
        b=int(input("\n\tExit Pres 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='december'):
        logo=pyfiglet.figlet_format("December")
        print(logo)
        print("=======================================================================================================================================================================")
        print("	                    Subject             1       2       3       4       5       6       7       8       9       10      11      12      13      14      15\n\t\t\t\t\t\t16      17      18      19      20      21      22      23      24      25      26      27      28      29      30")
        print("=======================================================================================================================================================================")
        print("1	CS3321 (Demystifying AIML	        P	N	P	N	P	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("2	CS3322 (Python Programming(S))	        N	N	N	N	P	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("3	CS3344 (Python Programming Lab	        N	N	N	N	N	N	P	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("4	CS3301 (Data Structure and Programming	N	P	P	N	P	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("5	CS3302 (Discrete Design Structure)	N	P	P,P	P	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("6	CS3305 (Database Management System(S))	N	N	P	P	P	N	N	N	P	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("7	CS3340 (Data Structure Programming Lab	N	P,P	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("8	EC3341 (Digital Electronics Lab(L))	N	N	N	P,P	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("9	CS3342 (Oracle/SQL Server Lab(L))	N	P,P	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("10	CS3346 (Project Lab I(L))	        P,P	N	N	N	N	N	N	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("11	VP3301 (Value Added Program III(L))	P,P	N	N	N	N	N	N	P,P	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("12	EC3306 (Digital Electronics(S))	        N	N	N	N	P,P	N	P	N	N	N	N	N	N	N	N	\n\t\t\t\t\t\tN	N	N	N	N	N	N	N	N	N	N	N	N	N	N")
        print("=======================================================================================================================================================================")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
    elif(a=='january'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='february'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='march'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='april'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='may'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='june'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    elif(a=='july'):
        print("No Data Found..........")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()
    else:
        print("Please Enter Valid Option............")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            months()
        else:
            print("Please Enter Valid Options.......")
            months()

#Analysis Exam Details

def exam_details():
    logo=pyfiglet.figlet_format("Exam Details")
    print(logo)
    print("\n\t<------- Exam Details --------->")
    print("\n\t1.) Semester 1")
    print("\n\t2.) Semester 2")
    print("\n\t3.) Exit")
    ch=int(input("Choose Any Options [1,3] ==> "))
    if(ch==1):
        print("\n\t\t\t\t\t\t\t\t\tQuantum University")
        print("\n\t\t\t\t\t\tRoorkee - Dehradun Highway , Mandawar,Roorkee,Uttrakhand 247167")
        print("\n\t\t\t\t\t\t\t\t   www.quantumuniversity.edu.in")
        print("\n\t\t\t\t\t\t\t\t  STATEMENT OF MARKS(PROVISIONAL)")
        print("\n\t\t\t\t\t   B.Tech(Computer Science & Engineering)-1 SEMESTER EXAMINATION (2019-2020)")
        print("\n\n\t\tName of Student : SAJEEV KUMAR PRAJAPATI\t\t\t\t\t\t\tEnrollment No : QU2701101925")
        print("\n\t\tFather's Name   : PQRST XYZ\t\t\t\t\t\t\t\t\t\tRoll No : 2701101925")
        print("\n")
        print("===============================================================================================================")
        print("                                                SUBJECT                        CREDITS   GRADE     GRADE POINT")
        print("===============================================================================================================")
        print("                  CODE                            NAME")
        print("===============================================================================================================")
        print("Theory           MA3102   Mathematics -1                                          4        A+          10.00")
        print("                 PH3101   Engineering Physics                                     3        A+          10.00")
        print("                 EG3102   Professional Communication                              2        B+           8.00")
        print("                 CS3101   Basic of Computer and C Programming                     4        A+          10.00")
        print("                 ME3102   Basic Mehanical Engineering                             3        B+           8.00")
        print("                 CE3102   Disaster Management*                                    2        B+           8.00")
        print("===============================================================================================================")
        print("Practical        PH3140   Engineering Physics Lab                                 1        A            9.00")
        print("                 EG3140   Professional Communication                              1        B            7.00")
        print("                 CS3140   Basic of Computer and C Programming                     1        A            9.00")
        print("                 VP3101   Personality Development Program                         1        C            5.00")
        print("                 GP3101   General Proficiency                                     1        A+           9.00")
        print("===============================================================================================================")
        print("\n\tSGPA :               9")
        print("\n\tCurrent CGPA :               9.00")
        print("\n\t% Equivalent to CGPA :       90")
        print("\n\nNote : This is  the System generated document and can not be used in official purpose")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            exam_details()
        else:
            print("Please Enter Valid Options.......")
    elif(ch==2):
        print("\n\t\t\t\t\t\t\t\t\tQuantum University")
        print("\n\t\t\t\t\t\tRoorkee - Dehradun Highway , Mandawar,Roorkee,Uttrakhand 247167")
        print("\n\t\t\t\t\t\t\t\t   www.quantumuniversity.edu.in")
        print("\n\t\t\t\t\t\t\t\t  STATEMENT OF MARKS(PROVISIONAL)")
        print("\n\t\t\t\t\t   B.Tech(Computer Science & Engineering)-2  SEMESTER EXAMINATION (2019-2020)")
        print("\n\n\t\tName of Student : SAJEEV KUMAR PRAJAPATI\t\t\t\t\t\t\tEnrollment No : QU2701101925")
        print("\n\t\tFather's Name   : PQRSTS XYZ\t\t\t\t\t\t\t\t\t\tRoll No : 2701101925")
        print("\n")
        print("===============================================================================================================")
        print("                                                SUBJECT                        CREDITS   GRADE     GRADE POINT")
        print("===============================================================================================================")
        print("                  CODE                            NAME")
        print("===============================================================================================================")
        print("Theory           CS3203   Graph Theory And Probability                            3        A           9.00")
        print("                 CS3206   Advance C Programming                                   4        A           9.00")
        print("                 CS3204   HTML5 & CSS                                             4        A+         10.00")
        print("                 CY3205   Environment Studies                                     2        A           9.00")
        print("                 CS3205   Web And Digital Analytics                               3        A           9.00")
        print("                 PS3101   Human Value And Ethics                                  2        A           9.00")
        print("===============================================================================================================")
        print("Practical        CS3242   Advance C Programming Lab                               1        A+         10.00")
        print("                 CS3243   HTML5 & CSS Lab                                         1        A           9.00")
        print("                 CS3244   Web And Digital Analytics Lab                           1        A           9.00")
        print("                 VP3204   Value Added Program                                     2        A           9.00")
        print("                 GP3201   General Proficiency                                     1        A+         10.00")
        print("===============================================================================================================")
        print("\n\tSGPA :               9.25")
        print("\n\tCurrent CGPA :               9.13")
        print("\n\t% Equivalent to CGPA :       91.3")
        print("\n\nNote : This is  the System generated document and can not be used in official purpose")
        b=int(input("\n\tExit Press 1 For Continue Press 2 : "))
        if(b==1):
            analysis_cal()
        elif(b==2):
            exam_details()
        else:
            print("Please Enter Valid Options.......")
    
#Months control function
            
def analysis_cal():
    print("\n\t<------- Analysis --------->")
    print("\n\t1.) Months Register")
    print("\n\t2.) Exam Details")
    print("\n\t3.) Exit")
    ch=int(input("Choose Any Options [1,3] ==> "))
    if(ch==1):
        months()
    elif(ch==2):
        exam_details()
    elif(ch==3):
        abc()
    else:
        print("Please Enter valid Options..........")
# Months Main function     
def analysis():
    analysis_show()
    analysis_cal()
    
# Main Body Of the Programe
def abc():
    print("\n\t\n\t\t\t\t\t\t\t\t\t1.) Academic")
    print("\n\t\n\t\t\t\t\t\t\t\t\t2.) Fee")
    print("\n\t\n\t\t\t\t\t\t\t\t\t3.) Circular")
    print("\n\t\n\t\t\t\t\t\t\t\t\t4.) Notifications")
    print("\n\t\n\t\t\t\t\t\t\t\t\t5.) Library")
    print("\n\t\n\t\t\t\t\t\t\t\t\t6.) Exam")
    print("\n\t\n\t\t\t\t\t\t\t\t\t7.) Placement")
    print("\n\t\n\t\t\t\t\t\t\t\t\t8.) Event")
    print("\n\t\n\t\t\t\t\t\t\t\t\t9.) Hostel")
    print("\n\t\n\t\t\t\t\t\t\t\t\t10.) Complaint Management System")
    print("\n\t\t\t\t\t\t\t\t\t11.) Analysis")
    print("\n\t\t\t\t\t\t\t\t\t12.) Exit")
    c=int(input("Choose Any Options [1,12] ==> "))
    if(c==1):
        academic()
    elif(c==2):
        fee()
    elif(c==3):
        circular()
    elif(c==4):
        logo=pyfiglet.figlet_format("Notification")
        print(logo)
        print("No Data Found........")
        abc()
    elif(c==5):
        logo=pyfiglet.figlet_format("Library")
        print(logo)
        print("No Data Found........")
        abc()
    elif(c==6):
        exam()
    elif(c==7):
        logo=pyfiglet.figlet_format("Placement")
        print(logo)
        print("No Data Found........")
        abc()
    elif(c==8):
        event()
    elif(c==9):
        logo=pyfiglet.figlet_format("Hostel")
        print(logo)
        print("No Data Found........")
        abc()
    elif(c==10):
        logo=pyfiglet.figlet_format("Complaint Management System")
        print(logo)
        print("You are not egligible to send complaint ........")
        abc()
    elif(c==11):
        logo=pyfiglet.figlet_format("Analysis")
        print(logo)
        analysis()
    elif(c==12):
        print("<!--------------- THANKYOU ----------------!>")
        exit()
    else:
        print("Please Enter Valid Options......")
        abc()
        
def after_login():
    print("=======================================================================================================================================================================")
    logo=pyfiglet.figlet_format("Quantum")
    logo1=pyfiglet.figlet_format("University")
    print(logo,logo1)
    print("\n\t\t\t\t\t\t\t\t\t======= QUANTUM =======")
    print("\n\t\t\t\t\t\t\t\t\t===== UNIVERSITY ======")
    print("\n\t\t\t\t\t\t\t\t\t     Cyborg - ERP")
    print("\n\t\t\t\t\t\t\t\t  Powered by Cyborg IT Services(P) Ltd.")
    print("\n\t\n\t\t\t\t\t\t\t\t\tSANJEEV KUMAR PRAJAPATI ")
    print("\n\t\t\t\t\t\t\t\t\t\t89070160")
    print("\n\t\t\t\t\t\t\t\tsk5672934@gmail.com")
    print("\n\t\t\t\t\t\t\t\t79XXXXX14")
    print("\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    Update Contact Information")
    print("\n\t\t\t\t\t\t\t\tFather Name : PQRSTS XYZ")
    print("\n\t\t\t\t\t\t\t\tMother Name : ABCDEFGH")
    print("\n\t\t\t\t\t\t\t\t      D.O.B : 10/02/2001")
    print("\n\t\t\t\t\t\t\t\t    College : School of Technology")
    print("\n\t\t\t\t\t\t\t\t     Course : B.Tech")
    print("\n\t\t\t\t\t\t\t     Specialization : B.Tech(Hons.)")
    print("\n\t\t\t\t\t\t\t\t   Year/Sem : 3")
    print("\n\t\t\t\t\t\t\t\t     Branch : (Hons) Computer Science & Engineering with\n\t\t\t\t\t\t\t\t\t      Specialization in AI and Machine Learning in\n\t\t\t\t\t\t\t\t\t       Collaboration with Xebia")
    print("\n\t\t\t\t\t\t\t\t    Section : N/A")
    print("\n\t\t\t\t\t\t\t\t  Enroll No : QU2701101925")
    print("\n\t\t\t\t\t\t\t University Roll No : 2701101925")
    print("\n\t\t\t\t\t\t\t       HighSchool % : 88.6")
    print("\n\t\t\t\t\t\t\t     Intermediate % : 74.8")
    abc()
def cap():
    aa=getpass.getpass("Enter New Password : ")
    print("\n\t",xxx)
    capt=input("\nEnter Captcha : ")
    if(capt==xxx):
            print("Your Password is Updating Wait for 10 sec ....................")
            time.sleep(10)
            print("Your Password Updated Successfully!!")
            ac=int(input("\t\t\t\t\t\t\t\t\tUSER ID : "))
            bd=getpass.getpass("\t\t\t\t\t\t\t\t\tPASSWORD : ")
            if(ac==19030120 and bd==aa):
                print("Loading.......")
                time.sleep(10)
                after_login()
    else:
        print("Please Enter Valid Captcha")
        cap()
def password():
    print("\n\t\t\t\t\t\t\t\t\t======= QUANTUM =======")
    print("\n\t\t\t\t\t\t\t\t\t===== UNIVERSITY ======")
    print("\n\t\t\t\t\t\t\t\t\t     Cyborg - ERP")
    print("\n\t\t\t\t\t\t\t\t  Powered by Cyborg IT Services(P) Ltd.")
    print("=======================================================================================================================================================================")
    a=int(input("\t\t\t\t\t\t\t\t\tUSER ID : "))
    b=getpass.getpass("\t\t\t\t\t\t\t\t\tPASSWORD : ")
    c=input("\t\t\t\t\t\t\t     Forgot Password [Y/N] : ").lower()
    if(c=='y'):
        #captcha
        cap()
    print("=======================================================================================================================================================================")
    if(a==19030120 and b=='python@123'):
        print("Loading.......")
        time.sleep(10)
        after_login()
    else:
        print("\t\t\t\t\t\t\t\t\tInvalid Username or password")
        password()
def login():
    logo=pyfiglet.figlet_format("ERP",font='doh')
    print(logo)
    password()
login()

